export default {
  records: [
    {
      id: 1,
      name: 'Track one',
      length: '1:24',
      src: 'https://json.wav',
      created: Date.now(),
      description: 'Small track in B Minor',
    },
    {
      id: 2,
      name: 'Track two',
      length: '2:56',
      src: 'something',
      created: Date.now(),
      description: 'No Description Provided',
    },
    {
      id: 3,
      name: 'Track one',
      length: '1:24',
      src: 'https://json.wav',
      created: Date.now(),
      description: 'Small track in B Minor',
    },
    {
      id: 4,
      name: 'Track one',
      length: '1:24',
      src: 'https://json.wav',
      created: Date.now(),
      description: 'Small track in B Minor',
    },
    {
      id: 5,
      name: 'Track one',
      length: '1:24',
      src: 'https://json.wav',
      created: Date.now(),
      description: 'Small track in B Minor',
    },
    {
      id: 6,
      name: 'Track one',
      length: '1:24',
      src: 'https://json.wav',
      created: Date.now(),
      description: 'Long Description Long Description Long Description Long Description Long Description Long Description Long Description Long Description Long Description Long Description Long Description Long Description',
    },
    {
      id: 7,
      name: 'Track one',
      length: '1:24',
      src: 'https://json.wav',
      created: Date.now(),
      description: 'Small track in B Minor',
    },
  ],
};
